{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-navigation3-helper/1.4.0-alpha03/compose-navigation3-helper-1.4.0-alpha03.module",
    "group": "com.github.devmre",
    "module": "compose-navigation3-helper",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compose-navigation3-helper-desktop-1.4.0-alpha03.jar",
          "url": "compose-navigation3-helper-desktop-1.4.0-alpha03.jar",
          "size": 16610,
          "sha512": "d286edd8eb0d032e112b80c1e5b02c467f4c21896d6131f9f904ac285993fdf10daeaa0d89b8a1438c2b225dacf153714f50ce2be4b936102041327a97dae48d",
          "sha256": "95ff9dd1172192c586423162a235a99f1e7f9d81f52ee949982af5237c9205a8",
          "sha1": "74e300bda93011681284d8c66ebb9afa56feb8af",
          "md5": "63289a2a3bbb8b583d1533f6e1ed6c7e"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation3-helper-desktop-1.4.0-alpha03.jar",
          "url": "compose-navigation3-helper-desktop-1.4.0-alpha03.jar",
          "size": 16610,
          "sha512": "d286edd8eb0d032e112b80c1e5b02c467f4c21896d6131f9f904ac285993fdf10daeaa0d89b8a1438c2b225dacf153714f50ce2be4b936102041327a97dae48d",
          "sha256": "95ff9dd1172192c586423162a235a99f1e7f9d81f52ee949982af5237c9205a8",
          "sha1": "74e300bda93011681284d8c66ebb9afa56feb8af",
          "md5": "63289a2a3bbb8b583d1533f6e1ed6c7e"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compose-navigation3-helper-desktop-1.4.0-alpha03-sources.jar",
          "url": "compose-navigation3-helper-desktop-1.4.0-alpha03-sources.jar",
          "size": 3974,
          "sha512": "be710c99f0e34d1d8ca6c5e6ce3c3412bdc55349000136ee9172e5ecf0722920e63258898a26cb25d9c0a65659bea6b230ab159cfd660bdc71c5aab691fc9311",
          "sha256": "f150ec0704191d9082cd8acfdfb126ec1d47dec9d341a9ba948e11937e7aa7a0",
          "sha1": "0455b4798c50a2544bae87e631918a53bcae6539",
          "md5": "88b004e6049185e9a1fe2c7248238142"
        }
      ]
    }
  ]
}
