{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.devmre",
    "module": "navigation3-helper",
    "version": "1.4.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "navigation3-helper-metadata-1.4.0-alpha07.jar",
          "url": "navigation3-helper-1.4.0-alpha07.jar",
          "size": 5582,
          "sha512": "fa3dffddb03b3550e6586ddceb73ffef7f0d28b913db05376d65e106d60e52853cf50748cf725bd06ea3450385b659c56d3693df5e820cfdc9a931eee44d7d9d",
          "sha256": "d9a35046f685a40b06adfaaa5f0875d726777292b0139a74a647714e3424e6a8",
          "sha1": "5732910b473a53d0790851073341ebb6e8a9eea9",
          "md5": "5ab420ef12bbf2eedabf0d93c50459cc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "navigation3-helper-kotlin-1.4.0-alpha07-sources.jar",
          "url": "navigation3-helper-1.4.0-alpha07-sources.jar",
          "size": 3996,
          "sha512": "59f85d7c64d9e2a62187ff0acc6f01c273edb337c2fcba4f98b7d7feccc48d4e835b68062c7d9dadeaeea31caa60474788782308d731169ffaaf815f1dfa8790",
          "sha256": "26a8eaf0b316c3a70aa8816f0c3abec666ce0bdfc2e2e9f028bacf2072e56483",
          "sha1": "d094be7b8337a60da1f92ba7c7b1506e9527b351",
          "md5": "76567167998fd7092e56199b1b02c27d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-helper-android/1.4.0-alpha07/navigation3-helper-android-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-android",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-helper-android/1.4.0-alpha07/navigation3-helper-android-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-android",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation3-helper-android/1.4.0-alpha07/navigation3-helper-android-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-android",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-helper-desktop/1.4.0-alpha07/navigation3-helper-desktop-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-desktop",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-helper-desktop/1.4.0-alpha07/navigation3-helper-desktop-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-desktop",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation3-helper-desktop/1.4.0-alpha07/navigation3-helper-desktop-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-desktop",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iosarm64/1.4.0-alpha07/navigation3-helper-iosarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iosarm64",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iosarm64/1.4.0-alpha07/navigation3-helper-iosarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iosarm64",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iosarm64/1.4.0-alpha07/navigation3-helper-iosarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iosarm64",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iosarm64/1.4.0-alpha07/navigation3-helper-iosarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iosarm64",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iossimulatorarm64/1.4.0-alpha07/navigation3-helper-iossimulatorarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iossimulatorarm64/1.4.0-alpha07/navigation3-helper-iossimulatorarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iossimulatorarm64/1.4.0-alpha07/navigation3-helper-iossimulatorarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha07"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation3-helper-iossimulatorarm64/1.4.0-alpha07/navigation3-helper-iossimulatorarm64-1.4.0-alpha07.module",
        "group": "com.github.devmre",
        "module": "navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha07"
      }
    }
  ]
}
