{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-navigation3-helper/1.4.0-alpha03/compose-navigation3-helper-1.4.0-alpha03.module",
    "group": "com.github.devmre",
    "module": "compose-navigation3-helper",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation3-helper-iosSimulatorArm64Main-1.4.0-alpha03.klib",
          "url": "compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha03.klib",
          "size": 19551,
          "sha512": "5421511d08349fb3c05c53e4c81a30ed86040eae0ef837896d2c280dd5d5dc2ebc219e9a22a2a5c62cd38c131172264568141f9ac125d43dcac144362b63f88b",
          "sha256": "1f1b9a1e92a0d239e87f807bbfaec6cf0df39548f5e80916ab8b55d245151276",
          "sha1": "b766792859f5524773d14f8a61a13dcc4af61687",
          "md5": "5c01f00dbc3b01f9cc2e6057c0a25ca3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha03-sources.jar",
          "url": "compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha03-sources.jar",
          "size": 3974,
          "sha512": "be710c99f0e34d1d8ca6c5e6ce3c3412bdc55349000136ee9172e5ecf0722920e63258898a26cb25d9c0a65659bea6b230ab159cfd660bdc71c5aab691fc9311",
          "sha256": "f150ec0704191d9082cd8acfdfb126ec1d47dec9d341a9ba948e11937e7aa7a0",
          "sha1": "0455b4798c50a2544bae87e631918a53bcae6539",
          "md5": "88b004e6049185e9a1fe2c7248238142"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation3-helper-1.4.0-alpha03.kotlin_resources.zip",
          "url": "compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha03-kotlin_resources.kotlin_resources.zip",
          "size": 376,
          "sha512": "da4d16e0e509acea8ff92e76b0c5c686428603f23fd1cfb2e87394ce9b0c9dec7821caed44cceb8f079c3a9765a01d9002eb92b6e01e91d914efe68319c061e1",
          "sha256": "f38957c6dc3a29a2b8e314727ff17138e9a1e932f7744dcec6f55c6844600dc9",
          "sha1": "ced9e35b882fa29c40f3e724b55d0aef2aa84618",
          "md5": "ac71e298072ecc58bfeff7081179fdb4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha03-metadata.jar",
          "url": "compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha03-metadata.jar",
          "size": 261,
          "sha512": "76976ce5c2f318c9263425244300ae935df50ebb9ae66110faf49539112d22b1890748054ee9876a80747827761353222c2a8f51be84d250cc0c0c70058733b4",
          "sha256": "ad40132e147716394f5ec5205ffcfe780c7d9250ad40f3977d459340cd146009",
          "sha1": "27deb3af11314c9cce27b784df5b5dc688d42ef4",
          "md5": "a680a53153619f11311680efbf842df9"
        }
      ]
    }
  ]
}
