{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.devmre",
    "module": "compose-navigation3-helper",
    "version": "1.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation3-helper-metadata-1.4.0-alpha04.jar",
          "url": "compose-navigation3-helper-1.4.0-alpha04.jar",
          "size": 5591,
          "sha512": "15d69e106ce3ddf22991139334890a5b7aafa1d48c58744f20316f81bc0f5df84aeeebcba8b55d238ffdaeefe72129632cff911e5f1bf87663d09977d92bc5e5",
          "sha256": "6ed586fc4307a486fe810a9f181af319664b37e5e6b804abcfc4ffe7e04b00cc",
          "sha1": "db49f9c3de628c1087aca4e866f73c1853d1c520",
          "md5": "de9066a3fd2673e9f4a1af292e31c079"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-navigation3-helper-kotlin-1.4.0-alpha04-sources.jar",
          "url": "compose-navigation3-helper-1.4.0-alpha04-sources.jar",
          "size": 3996,
          "sha512": "59f85d7c64d9e2a62187ff0acc6f01c273edb337c2fcba4f98b7d7feccc48d4e835b68062c7d9dadeaeea31caa60474788782308d731169ffaaf815f1dfa8790",
          "sha256": "26a8eaf0b316c3a70aa8816f0c3abec666ce0bdfc2e2e9f028bacf2072e56483",
          "sha1": "d094be7b8337a60da1f92ba7c7b1506e9527b351",
          "md5": "76567167998fd7092e56199b1b02c27d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-android/1.4.0-alpha04/compose-navigation3-helper-android-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-android",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-android/1.4.0-alpha04/compose-navigation3-helper-android-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-android",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-android/1.4.0-alpha04/compose-navigation3-helper-android-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-android",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-desktop/1.4.0-alpha04/compose-navigation3-helper-desktop-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-desktop",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-desktop/1.4.0-alpha04/compose-navigation3-helper-desktop-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-desktop",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-desktop/1.4.0-alpha04/compose-navigation3-helper-desktop-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-desktop",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iosarm64/1.4.0-alpha04/compose-navigation3-helper-iosarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iosarm64",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iosarm64/1.4.0-alpha04/compose-navigation3-helper-iosarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iosarm64",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iosarm64/1.4.0-alpha04/compose-navigation3-helper-iosarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iosarm64",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iosarm64/1.4.0-alpha04/compose-navigation3-helper-iosarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iosarm64",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iossimulatorarm64/1.4.0-alpha04/compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iossimulatorarm64/1.4.0-alpha04/compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iossimulatorarm64/1.4.0-alpha04/compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-navigation3-helper-iossimulatorarm64/1.4.0-alpha04/compose-navigation3-helper-iossimulatorarm64-1.4.0-alpha04.module",
        "group": "com.github.devmre",
        "module": "compose-navigation3-helper-iossimulatorarm64",
        "version": "1.4.0-alpha04"
      }
    }
  ]
}
